# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Junbo Zheng
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^src/lvglimg/
        additional_dependencies: ["Pillow>=10.0", "lz4>=4.0"]
